# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 261588e961fad3bb870c9c1954639691e299798ddb99e5e8d99309c52eb38f2c7ea255a836924016fb76683cb2b759aced83690862ebefae0b370ba018c71ec5

test:
  secret_key_base: 539f618230052a2d42ea8f295c72b0cc9a6566046d77c8851fd9723aaf885d42bfa5845b961e06350865444cf868ee1527409b1ae6f09a8445443a52099e3eb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
